<?php

return [
    'schema_version' => '0.3',
    'api_version' => 'v1',
    'exposures' => [
        ['id' => 'public', 'label' => 'Público'],
        ['id' => 'authenticated', 'label' => 'Autenticado'],
        ['id' => 'admin', 'label' => 'Administrador'],
        ['id' => 'internal', 'label' => 'Interno'],
    ],
    'governance' => [
        'authentication_strategies' => [
            ['id' => 'none', 'label' => 'Sin autenticación'],
            ['id' => 'sanctum', 'label' => 'Laravel Sanctum'],
        ],
        'pagination_strategies' => [
            ['id' => 'cursor', 'label' => 'Cursor'],
            ['id' => 'offset', 'label' => 'Offset'],
        ],
        'defaults' => [
            'authentication' => 'sanctum',
            'rbac' => true,
            'correlation_id' => true,
            'rate_limiting' => [
                'enabled' => true,
                'requests_per_minute' => 60,
            ],
            'pagination' => [
                'strategy' => 'cursor',
                'default_size' => 25,
                'max_size' => 100,
            ],
            'filtering' => true,
            'sorting' => true,
            'idempotency' => true,
            'audit' => true,
        ],
    ],
    'templates' => [
        [
            'id' => 'blank',
            'name' => 'API en blanco',
            'description' => 'Comienza desde un contrato vacío y habilita solamente lo que el producto necesita.',
            'endpoints' => [],
        ],
        [
            'id' => 'crud',
            'name' => 'REST CRUD',
            'description' => 'Recurso de clientes compacto con operaciones estándar de lectura y escritura.',
            'endpoints' => ['customers.list', 'customers.show', 'customers.create', 'customers.update'],
        ],
        [
            'id' => 'saas',
            'name' => 'SaaS inicial',
            'description' => 'Autenticación, usuarios, roles y auditoría para una API SaaS gobernada.',
            'endpoints' => ['auth.login', 'auth.logout', 'users.list', 'users.show', 'users.create', 'users.update', 'roles.list', 'audit.list'],
        ],
        [
            'id' => 'commerce',
            'name' => 'Comercio inicial',
            'description' => 'Clientes, productos y pedidos con una superficie pública intencionalmente pequeña.',
            'endpoints' => ['auth.login', 'customers.list', 'customers.show', 'customers.create', 'products.list', 'products.show', 'orders.list', 'orders.show', 'orders.create'],
        ],
    ],
    'exposure_dependencies' => [
        'authenticated' => ['auth.login'],
        'admin' => ['auth.login'],
        'internal' => ['auth.login'],
    ],
    'endpoint_dependencies' => [
        'auth.logout' => ['auth.login'],
        'payments.create' => ['orders.show'],
    ],
    'endpoints' => [
        ['id' => 'auth.login', 'capability' => 'authentication', 'capability_label' => 'Autenticación', 'summary' => 'Iniciar sesión', 'method' => 'POST', 'path' => '/api/v1/auth/login', 'default_exposure' => 'public'],
        ['id' => 'auth.logout', 'capability' => 'authentication', 'capability_label' => 'Autenticación', 'summary' => 'Cerrar sesión', 'method' => 'POST', 'path' => '/api/v1/auth/logout', 'default_exposure' => 'authenticated'],
        ['id' => 'users.list', 'capability' => 'users', 'capability_label' => 'Usuarios', 'summary' => 'Listar usuarios', 'method' => 'GET', 'path' => '/api/v1/users', 'default_exposure' => 'admin'],
        ['id' => 'users.show', 'capability' => 'users', 'capability_label' => 'Usuarios', 'summary' => 'Obtener usuario', 'method' => 'GET', 'path' => '/api/v1/users/{id}', 'default_exposure' => 'admin'],
        ['id' => 'users.create', 'capability' => 'users', 'capability_label' => 'Usuarios', 'summary' => 'Crear usuario', 'method' => 'POST', 'path' => '/api/v1/users', 'default_exposure' => 'admin'],
        ['id' => 'users.update', 'capability' => 'users', 'capability_label' => 'Usuarios', 'summary' => 'Actualizar usuario', 'method' => 'PUT', 'path' => '/api/v1/users/{id}', 'default_exposure' => 'admin'],
        ['id' => 'users.delete', 'capability' => 'users', 'capability_label' => 'Usuarios', 'summary' => 'Eliminar usuario', 'method' => 'DELETE', 'path' => '/api/v1/users/{id}', 'default_exposure' => 'admin'],
        ['id' => 'roles.list', 'capability' => 'roles', 'capability_label' => 'Roles y permisos', 'summary' => 'Listar roles', 'method' => 'GET', 'path' => '/api/v1/roles', 'default_exposure' => 'admin'],
        ['id' => 'audit.list', 'capability' => 'audit', 'capability_label' => 'Auditoría', 'summary' => 'Listar eventos de auditoría', 'method' => 'GET', 'path' => '/api/v1/audit-events', 'default_exposure' => 'internal'],
        ['id' => 'customers.list', 'capability' => 'customers', 'capability_label' => 'Clientes', 'summary' => 'Listar clientes', 'method' => 'GET', 'path' => '/api/v1/customers', 'default_exposure' => 'authenticated'],
        ['id' => 'customers.show', 'capability' => 'customers', 'capability_label' => 'Clientes', 'summary' => 'Obtener cliente', 'method' => 'GET', 'path' => '/api/v1/customers/{id}', 'default_exposure' => 'authenticated'],
        ['id' => 'customers.create', 'capability' => 'customers', 'capability_label' => 'Clientes', 'summary' => 'Crear cliente', 'method' => 'POST', 'path' => '/api/v1/customers', 'default_exposure' => 'authenticated'],
        ['id' => 'customers.update', 'capability' => 'customers', 'capability_label' => 'Clientes', 'summary' => 'Actualizar cliente', 'method' => 'PUT', 'path' => '/api/v1/customers/{id}', 'default_exposure' => 'authenticated'],
        ['id' => 'customers.delete', 'capability' => 'customers', 'capability_label' => 'Clientes', 'summary' => 'Eliminar cliente', 'method' => 'DELETE', 'path' => '/api/v1/customers/{id}', 'default_exposure' => 'admin'],
        ['id' => 'products.list', 'capability' => 'products', 'capability_label' => 'Productos', 'summary' => 'Listar productos', 'method' => 'GET', 'path' => '/api/v1/products', 'default_exposure' => 'public'],
        ['id' => 'products.show', 'capability' => 'products', 'capability_label' => 'Productos', 'summary' => 'Obtener producto', 'method' => 'GET', 'path' => '/api/v1/products/{id}', 'default_exposure' => 'public'],
        ['id' => 'products.create', 'capability' => 'products', 'capability_label' => 'Productos', 'summary' => 'Crear producto', 'method' => 'POST', 'path' => '/api/v1/products', 'default_exposure' => 'admin'],
        ['id' => 'orders.list', 'capability' => 'orders', 'capability_label' => 'Pedidos', 'summary' => 'Listar pedidos', 'method' => 'GET', 'path' => '/api/v1/orders', 'default_exposure' => 'authenticated'],
        ['id' => 'orders.show', 'capability' => 'orders', 'capability_label' => 'Pedidos', 'summary' => 'Obtener pedido', 'method' => 'GET', 'path' => '/api/v1/orders/{id}', 'default_exposure' => 'authenticated'],
        ['id' => 'orders.create', 'capability' => 'orders', 'capability_label' => 'Pedidos', 'summary' => 'Crear pedido', 'method' => 'POST', 'path' => '/api/v1/orders', 'default_exposure' => 'authenticated'],
        ['id' => 'payments.create', 'capability' => 'payments', 'capability_label' => 'Pagos', 'summary' => 'Crear pago', 'method' => 'POST', 'path' => '/api/v1/payments', 'default_exposure' => 'authenticated'],
        ['id' => 'files.upload', 'capability' => 'files', 'capability_label' => 'Archivos', 'summary' => 'Subir archivo', 'method' => 'POST', 'path' => '/api/v1/files', 'default_exposure' => 'authenticated'],
        ['id' => 'webhooks.receive', 'capability' => 'webhooks', 'capability_label' => 'Webhooks', 'summary' => 'Recibir webhook', 'method' => 'POST', 'path' => '/api/v1/webhooks/{provider}', 'default_exposure' => 'public'],
    ],
];
